#!/bin/bash
clear
#--------------------------
# SCRIPT SSH-PLUS
# CANAL TELEGRAM: @NET_SATOSHI
#--------------------------

# - Cores
RED='\033[1;31m'
YELLOW='\033[1;33m'
SCOLOR='\033[0m'

# - Verifica Execução Como Root
if [[ "$EUID" -ne 0 ]]; then
    echo -e "${RED}[x] ¡DEBES EJECUTAR COMO USUARIO ROOT!${SCOLOR}"
    exit 1
fi

# - Verifica Arquitetura Compatível
case "$(uname -m)" in
    'amd64' | 'x86_64')
        arch='64'
        ;;
    'aarch64' | 'armv8')
        arch='arm64'
        ;;
    *)
        echo -e "${RED}[x] ¡ARQUITECTURA INCOMPATIBLE!${SCOLOR}"
        exit 1
        ;;
esac

# - Verifica OS Compatível
if grep -qs "ubuntu" /etc/os-release; then
    os_version=$(grep 'VERSION_ID' /etc/os-release | cut -d '"' -f 2 | tr -d '.')
    if [[ "$os_version" -lt 2004 ]]; then
        echo -e "${RED}[x] ¡VERSIÓN UBUNTU INCOMPATIBLE!\n${YELLOW}[!] ¡REQUIERE UBUNTU 20.04 O SUPERIOR!${SCOLOR}"
        exit 1
    fi
elif [[ -e /etc/debian_version ]]; then
    os_version=$(grep -oE '[0-10]+' /etc/debian_version | head -1)
    if [[ "$os_version" -lt 10 ]]; then
        echo -e "${RED}[x] ¡VERSIÓN DEBIAN INCOMPATIBLE!\n${YELLOW}[!] ¡REQUIERE DEBIAN 10 O SUPERIOR!${SCOLOR}"
        exit 1
    fi
else
    echo -e "${RED}[x] OS INCOMPATIBLE!\n${YELLOW}[!] ¡REQUIERE DISTROS BASE DEBIAN/UBUNTU!${SCOLOR}"
    exit 1
fi

# - Atualiza Lista/Pacotes/Sistema
dpkg --configure -a
apt update -y && apt upgrade -y
apt install unzip python3 -y

# - Desabilita IPv6
sysctl -w net.ipv6.conf.all.disable_ipv6=1 && sysctl -p
echo 'net.ipv6.conf.all.disable_ipv6 = 1' > /etc/sysctl.d/70-disable-ipv6.conf
sysctl -p -f /etc/sysctl.d/70-disable-ipv6.conf

# - Executa Instalador
if [[ -e Plus ]]; then
    rm Plus
fi
wget https://github.com/Satoshi-v/webcont_script/main/script/${arch}/Plus && chmod 777 Plus && ./Plus
