#!/bin/bash
clear
#--------------------------
# SCRIPT SSH-PLUS
# CANAL TELEGRAM: @TURBONET2023
#--------------------------

# - Cores
RED='\033[1;31m'
YELLOW='\033[1;33m'
GREEN='\033[1;32m'
SCOLOR='\033[0m'

# - Funções
function verifica_root() {
    if [[ "$EUID" -ne 0 ]]; then
        echo -e "${RED}[x] Você precisa executar como usuário root!${SCOLOR}"
        exit 1
    fi
}

function verifica_arquitetura() {
    case "$(uname -m)" in
        'amd64' | 'x86_64')
            arch='64'
            ;;
        'aarch64' | 'armv8')
            arch='arm64'
            ;;
        *)
            echo -e "${RED}[x] Arquitetura incompatível!${SCOLOR}"
            exit 1
            ;;
    esac
}

function verifica_os() {
    if grep -qs "ubuntu" /etc/os-release; then
        os_version=$(grep 'VERSION_ID' /etc/os-release | cut -d '"' -f 2 | tr -d '.')
        if [[ "$os_version" -lt 1804 ]]; then
            echo -e "${RED}[x] Versão do Ubuntu incompatível!\n${YELLOW}[!] Requer Ubuntu 18.04 ou superior!${SCOLOR}"
            exit 1
        fi
    elif [[ -e /etc/debian_version ]]; then
        os_version=$(grep -oE '[0-9]+' /etc/debian_version | head -1)
        if [[ "$os_version" -lt 9 ]]; then
            echo -e "${RED}[x] Versão do Debian incompatível!\n${YELLOW}[!] Requer Debian 9 ou superior!${SCOLOR}"
            exit 1
        fi
    else
        echo -e "${RED}[x] Sistema operacional incompatível!\n${YELLOW}[!] Requer distros base Debian/Ubuntu!${SCOLOR}"
        exit 1
    fi
}

function verifica_pacote() {
    if ! dpkg -l | grep -q "$1"; then
        echo -e "${YELLOW}[!] Instalando $1...${SCOLOR}"
        apt-get install -y "$1" || { echo -e "${RED}[x] Falha ao instalar $1!${SCOLOR}"; exit 1; }
    fi
}

function atualiza_sistema() {
    echo -e "${YELLOW}[!] Atualizando o sistema...${SCOLOR}"
    dpkg --configure -a
    apt-get update -y && apt-get upgrade -y
    verifica_pacote unzip
    verifica_pacote python3
    verifica_pacote wget
}

function desabilita_ipv6() {
    echo -e "${YELLOW}[!] Desabilitando IPv6...${SCOLOR}"
    sysctl -w net.ipv6.conf.all.disable_ipv6=1 && sysctl -p
    echo 'net.ipv6.conf.all.disable_ipv6 = 1' > /etc/sysctl.d/70-disable-ipv6.conf
    sysctl -p -f /etc/sysctl.d/70-disable-ipv6.conf
}

function executa_instalador() {
    if command -v wget >/dev/null 2>&1; then
        echo -e "${YELLOW}[!] Baixando e executando o instalador...${SCOLOR}"
        [[ -e Plus ]] && rm Plus
        wget -q https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/script/64/Plus -O Plus
        chmod 777 Plus
        ./Plus
    else
        echo -e "${RED}[x] wget não está instalado e não pode ser instalado!${SCOLOR}"
        exit 1
    fi
}

# - Execução
verifica_root
verifica_arquitetura
verifica_os
atualiza_sistema
desabilita_ipv6
executa_instalador
