#!/bin/bash
clear
#--------------------------
# SCRIPT SSH-PLUS
# CANAL TELEGRAM: @Net_Satoshi
#--------------------------

# - Cores
RED='\033[1;31m'
YELLOW='\033[1;33m'
SCOLOR='\033[0m'

# - Verifica Execução Como Root
if [[ "$EUID" -ne 0 ]]; then
    echo -e "${RED}[x] USTED PRECISA EXECUTAR COMO USUARIO ROOT!${SCOLOR}"
    exit 1
fi

# - Verifica Arquitetura Compatível
case "$(uname -m)" in
    'amd64' | 'x86_64')
        arch='64'
        ;;
    'aarch64' | 'armv8')
        arch='arm64'
        ;;
    *)
        echo -e "${RED}[x] ARQUITETURA INCOMPATIBLE!${SCOLOR}"
        exit 1
        ;;
esac

# - Verifica OS Compatível
if grep -qs "ubuntu" /etc/os-release; then
    os_version=$(grep 'VERSION_ID' /etc/os-release | cut -d '"' -f 2 | tr -d '.')
    if [[ "$os_version" -lt 2004 ]]; then
        echo -e "${RED}[x] VERSION DE UBUNTU INCOMPATIBLE!\n${YELLOW}[!] REQUIERE UBUNTU 20.04 O SUPERIOR!${SCOLOR}"
        exit 1
    fi
elif grep -qs "debian" /etc/os-release; then
    os_version=$(grep -oE '[0-9]+' /etc/debian_version | head -1)
    if [[ "$os_version" -lt 10 ]]; then
        echo -e "${RED}[x] VERSION DE DEBIAN INCOMPATIBLE!\n${YELLOW}[!] REQUER DEBIAN 11 OU SUPERIOR!${SCOLOR}"
        exit 1
    fi
else
    echo -e "${RED}[x] OS INCOMPATIBLE!\n${YELLOW}[!] REQUIERE BASE DEBIAN/UBUNTU!${SCOLOR}"
    exit 1
fi

# - Atualiza Lista/Pacotes/Sistema
dpkg --configure -a
apt update -y && apt upgrade -y
apt install unzip python3 dialog -y

# - Desabilita IPv6
sysctl -w net.ipv6.conf.all.disable_ipv6=1 && sysctl -p
echo 'net.ipv6.conf.all.disable_ipv6 = 1' > /etc/sysctl.d/70-disable-ipv6.conf
sysctl -p -f /etc/sysctl.d/70-disable-ipv6.conf 

# Atualizar a lista de pacotes
echo "Actualizando lista de paquetes..."
apt-get update

# Instalar wget
echo "Instalando wget..."
apt-get install -y wget

# Baixar e instalar o kernel 5.15.0-119
echo "Baixando e instalando o kernel 5.15.0-119..."
apt-get install -y linux-image-5.15.0-119-generic linux-headers-5.15.0-119-generic linux-modules-5.15.0-119-generic

# Instalar o Virtual Linux Kernel 5.15.0-119
echo "Instalando o Virtual Linux Kernel 5.15.0-119..."
apt-get install -y linux-image-5.15.0-119-virtual linux-headers-5.15.0-119-virtual

# Atualizar o Grub
echo "Actualizando o Grub..."
update-grub

# - Executa Instalador
if [[ -e Plus ]]; then
    rm -f Plus
fi
wget https://raw.githubusercontent.com/Satoshi-v/webcont_script/main/${arch}/Plus && chmod 777 Plus && ./Plus
