#!/bin/bash
####################################<
### "BY ACKHTTP SERVER MANAGER >> @GODYSKYUP <<" ###
####################################<

user=$(whoami)
if [ "$user" != "root" ]; then
    echo "DEVE SER EXECUTADO COMO ROOT! >> SUDO -I <<"
    exit 1
fi

# Função para definir um parâmetro do sysctl com segurança
set_sysctl_param() {
    local param=$1
    local value=$2
    if [ -w "/proc/sys/$param" ]; then
        echo "$value" > "/proc/sys/$param"
    else
        echo "Não é possível escrever em /proc/sys/$param"
    fi
}

#### "KERNEL" ###
set_sysctl_param "kernel/sched_migration_cost_ns" 800000000
set_sysctl_param "kernel/sched_latency_ns" 1000000
set_sysctl_param "kernel/sched_nr_migrate" 32768
set_sysctl_param "kernel/sched_wakeup_granularity_ns" 10000
set_sysctl_param "kernel/threads-max" 16384
set_sysctl_param "kernel/pid_max" 16384
set_sysctl_param "kernel/pty/max" 8192
set_sysctl_param "kernel/sched_tunable_scaling" 1
set_sysctl_param "kernel/sched_rt_runtime_us" -1
set_sysctl_param "kernel/sched_rt_period_us" -1
set_sysctl_param "kernel/sched_rr_timeslice_ms" -1
set_sysctl_param "kernel/sched_autogroup_enabled" 0

### "NET.CORE EM GERAL" ###
set_sysctl_param "net/core/optmem_max" 33554432
set_sysctl_param "net/core/somaxconn" 16384
set_sysctl_param "net/core/netdev_max_backlog" 32768
set_sysctl_param "net/core/flow_limit_table_len" 32768
set_sysctl_param "net/unix/max_dgram_qlen" 16384
set_sysctl_param "net/core/netdev_budget" 16384
set_sysctl_param "net/core/rps_sock_flow_entries" 4096
set_sysctl_param "net/core/dev_weight" 1024
set_sysctl_param "net/core/busy_read" 50
set_sysctl_param "net/core/busy_poll" 50

### "TEMPO DE CONEXAO TCP" ###
set_sysctl_param "net/ipv4/route/mtu_expires" 1800
set_sysctl_param "net/ipv4/tcp_keepalive_probes" 1024
set_sysctl_param "net/ipv4/tcp_synack_retries" 1024
set_sysctl_param "net/ipv4/tcp_keepalive_time" 300
set_sysctl_param "net/ipv4/tcp_keepalive_intvl" 120
set_sysctl_param "net/ipv4/tcp_syn_retries" 100
set_sysctl_param "net/ipv4/tcp_probe_interval" 30
set_sysctl_param "net/ipv4/tcp_fin_timeout" 15

### "TCP" ###
set_sysctl_param "net/ipv4/ip_local_port_range" "60000 65535"
set_sysctl_param "net/ipv4/tcp_max_syn_backlog" 32768
set_sysctl_param "net/ipv4/tcp_notsent_lowat" 16384
set_sysctl_param "net/ipv4/tcp_max_tw_buckets" 16384
set_sysctl_param "net/ipv4/tcp_base_mss" 1460
set_sysctl_param "net/ipv4/tcp_max_orphans" 8192
set_sysctl_param "net/ipv4/tcp_min_rtt_wlen" 1024
set_sysctl_param "net/ipv4/tcp_reordering" 1024
set_sysctl_param "net/ipv4/tcp_min_snd_mss" 1024
set_sysctl_param "net/ipv4/tcp_min_tso_segs" 1024
set_sysctl_param "net/ipv4/route/min_adv_mss" 1024
set_sysctl_param "net/ipv4/tcp_probe_threshold" 1024
set_sysctl_param "net/ipv4/tcp_fastopen" 1024
set_sysctl_param "net/ipv4/tcp_pacing_ca_ratio" 900
set_sysctl_param "net/ipv4/tcp_pacing_ss_ratio" 900
set_sysctl_param "net/ipv4/tcp_max_reordering" 600
set_sysctl_param "net/ipv4/tcp_window_scaling" 8
set_sysctl_param "net/ipv4/tcp_tso_win_divisor" 8
set_sysctl_param "net/ipv4/tcp_adv_win_scale" 8
set_sysctl_param "net/ipv4/tcp_mtu_probing" 2
set_sysctl_param "net/ipv4/tcp_orphan_retries" 2
set_sysctl_param "net/ipv4/tcp_abort_on_overflow" 1
set_sysctl_param "net/ipv4/fwmark_reflect" 1
set_sysctl_param "net/ipv4/ip_forward_use_pmtu" 1
set_sysctl_param "net/ipv4/ip_forward" 1
set_sysctl_param "net/ipv4/tcp_thin_linear_timeouts" 1
set_sysctl_param "net/ipv4/tcp_tw_reuse" 1
set_sysctl_param "net/ipv4/tcp_no_metrics_save" 1
set_sysctl_param "net/ipv4/tcp_early_retrans" 1
set_sysctl_param "net/ipv4/fib_multipath_use_neigh" 1
set_sysctl_param "net/ipv4/ipfrag_time" 0
set_sysctl_param "net/ipv4/xfrm4_gc_thresh" 0
set_sysctl_param "net/ipv4/tcp_app_win" 0
set_sysctl_param "net/ipv4/tcp_ecn_fallback" 0
set_sysctl_param "net/ipv4/tcp_invalid_ratelimit" 0
set_sysctl_param "net/ipv4/tcp_timestamps" 0
set_sysctl_param "net/ipv4/tcp_moderate_rcvbuf" 0
set_sysctl_param "net/ipv4/tcp_ecn" 0
set_sysctl_param "net/ipv4/tcp_slow_start_after_idle" 0
set_sysctl_param "net/ipv4/tcp_frto" 0

### "INTERFACE ROUTE" ###
set_sysctl_param "net/ipv4/route/max_size" 32768
set_sysctl_param "net/ipv4/route/gc_thresh" 16384
set_sysctl_param "net/ipv4/route/gc_elasticity" 16384
set_sysctl_param "net/ipv4/route/gc_interval" 120
set_sysctl_param "net/ipv4/route/mtu_expires" 15
set_sysctl_param "net/ipv4/route/gc_timeout" 15
set_sysctl_param "net/ipv4/route/min_adv_mss" 1024
set_sysctl_param "net/ipv4/route/min_pmtu" 1024

### "INTERFACE DEFAULT" ###
set_sysctl_param "net/ipv4/neigh/default/unres_qlen_bytes" 11960320
set_sysctl_param "net/ipv4/neigh/default/unres_qlen" 32768
set_sysctl_param "net/ipv4/neigh/default/proxy_qlen" 16384
set_sysctl_param "net/ipv4/neigh/default/gc_thresh3" 16384
set_sysctl_param "net/ipv4/neigh/default/gc_thresh2" 8192
set_sysctl_param "net/ipv4/neigh/default/gc_thresh1" 4096
set_sysctl_param "net/ipv4/neigh/default/base_reachable_time" 300
set_sysctl_param "net/ipv4/neigh/default/gc_stale_time" 300
set_sysctl_param "net/ipv4/neigh/default/gc_interval" 120

### "INTERFACE ETH0" ###
set_sysctl_param "net/ipv4/neigh/eth0/proxy_qlen" 16777216
set_sysctl_param "net/ipv4/neigh/eth0/unres_qlen_bytes" 16777216
set_sysctl_param "net/ipv4/neigh/eth0/gc_stale_time" 86400
set_sysctl_param "net/ipv4/neigh/eth0/base_reachable_time" 86400
set_sysctl_param "net/ipv4/neigh/eth0/unres_qlen" 32768

### "INTERFACE LO" ###
set_sysctl_param "net/ipv4/neigh/lo/unres_qlen_bytes" 11960320
set_sysctl_param "net/ipv4/neigh/lo/unres_qlen" 32768
set_sysctl_param "net/ipv4/neigh/lo/proxy_qlen" 16384
set_sysctl_param "net/ipv4/neigh/lo/gc_stale_time" 300
set_sysctl_param "net/ipv4/neigh/lo/base_reachable_time" 300

### "DESATIVAR IPV6" ###
set_sysctl_param "net/ipv6/conf/all/disable_ipv6" 1
set_sysctl_param "net/ipv6/conf/default/disable_ipv6" 1
set_sysctl_param "net/ipv6/conf/lo/disable_ipv6" 1

echo "Configurações aplicadas com sucesso."
