#!/bin/bash

####################################<
### "BY ACKHTTP SERVER MANAGER >> @GODYSKYUP <<" ###
####################################<

# Verifica se o script está sendo executado como root
if [ "$(whoami)" != "root" ]; then
  echo "DEVE SER EXECUTADO COMO ROOT! >> SUDO -I <<"
  exit 1
fi

set_sysctl() {
  echo $2 > $1
}

# Função para configurar parâmetros do kernel
configure_kernel() {
  set_sysctl /proc/sys/kernel/sched_migration_cost_ns 800000000
  set_sysctl /proc/sys/kernel/sched_latency_ns 1000000
  set_sysctl /proc/sys/kernel/sched_nr_migrate 32768
  set_sysctl /proc/sys/kernel/sched_wakeup_granularity_ns 10000
  set_sysctl /proc/sys/kernel/threads-max 16384
  set_sysctl /proc/sys/kernel/pid_max 16384
  set_sysctl /proc/sys/kernel/pty/max 8192
  set_sysctl /proc/sys/kernel/sched_tunable_scaling 1
  set_sysctl /proc/sys/kernel/sched_rt_runtime_us -1
  set_sysctl /proc/sys/kernel/sched_rt_period_us -1
  set_sysctl /proc/sys/kernel/sched_rr_timeslice_ms -1
  set_sysctl /proc/sys/kernel/sched_autogroup_enabled 0
}

# Função para configurar parâmetros de rede
configure_network_core() {
  set_sysctl /proc/sys/net/core/optmem_max 33554432
  set_sysctl /proc/sys/net/core/somaxconn 16384
  set_sysctl /proc/sys/net/core/netdev_max_backlog 32768
  set_sysctl /proc/sys/net/core/flow_limit_table_len 32768
  set_sysctl /proc/sys/net/unix/max_dgram_qlen 16384
  set_sysctl /proc/sys/net/core/netdev_budget 16384
  set_sysctl /proc/sys/net/core/rps_sock_flow_entries 4096
  set_sysctl /sys/class/net/eth0/queues/rx-0/rps_flow_cnt 4096
  set_sysctl /proc/sys/net/core/dev_weight 1024
  set_sysctl /proc/sys/net/core/busy_read 50
  set_sysctl /proc/sys/net/core/busy_poll 50
}

# Função para configurar parâmetros TCP
configure_tcp() {
  set_sysctl /proc/sys/net/ipv4/route/mtu_expires 1800
  set_sysctl /proc/sys/net/ipv4/tcp_keepalive_probes 1024
  set_sysctl /proc/sys/net/ipv4/tcp_synack_retries 1024
  set_sysctl /proc/sys/net/ipv4/tcp_keepalive_time 300
  set_sysctl /proc/sys/net/ipv4/tcp_keepalive_intvl 120
  set_sysctl /proc/sys/net/ipv4/tcp_syn_retries 100
  set_sysctl /proc/sys/net/ipv4/tcp_probe_interval 30
  set_sysctl /proc/sys/net/ipv4/tcp_fin_timeout 15
  set_sysctl /proc/sys/net/ipv4/ip_local_port_range "60000 65535"
  set_sysctl /proc/sys/net/ipv4/tcp_max_syn_backlog 32768
  set_sysctl /proc/sys/net/ipv4/tcp_notsent_lowat 16384
  set_sysctl /proc/sys/net/ipv4/tcp_max_tw_buckets 16384
  set_sysctl /proc/sys/net/ipv4/tcp_base_mss 1460
  set_sysctl /proc/sys/net/ipv4/tcp_max_orphans 8192
  set_sysctl /proc/sys/net/ipv4/tcp_min_rtt_wlen 1024
  set_sysctl /proc/sys/net/ipv4/tcp_reordering 1024
  set_sysctl /proc/sys/net/ipv4/tcp_min_snd_mss 1024
  set_sysctl /proc/sys/net/ipv4/tcp_min_tso_segs 1024
  set_sysctl /proc/sys/net/ipv4/route/min_adv_mss 1024
  set_sysctl /proc/sys/net/ipv4/tcp_probe_threshold 1024
  set_sysctl /proc/sys/net/ipv4/tcp_fastopen 1024
  set_sysctl /proc/sys/net/ipv4/tcp_pacing_ca_ratio 900
  set_sysctl /proc/sys/net/ipv4/tcp_pacing_ss_ratio 900
  set_sysctl /proc/sys/net/ipv4/tcp_max_reordering 600
  set_sysctl /proc/sys/net/ipv4/tcp_window_scaling 8
  set_sysctl /proc/sys/net/ipv4/tcp_tso_win_divisor 8
  set_sysctl /proc/sys/net/ipv4/tcp_adv_win_scale 8
  set_sysctl /proc/sys/net/ipv4/tcp_mtu_probing 2
  set_sysctl /proc/sys/net/ipv4/tcp_orphan_retries 2
  set_sysctl /proc/sys/net/ipv4/tcp_abort_on_overflow 1
  set_sysctl /proc/sys/net/ipv4/fwmark_reflect 1
  set_sysctl /proc/sys/net/ipv4/ip_forward_use_pmtu 1
  set_sysctl /proc/sys/net/ipv4/ip_forward 1
  set_sysctl /proc/sys/net/ipv4/tcp_thin_linear_timeouts 1
  set_sysctl /proc/sys/net/ipv4/tcp_tw_reuse 1
  set_sysctl /proc/sys/net/ipv4/tcp_no_metrics_save 1
  set_sysctl /proc/sys/net/ipv4/tcp_early_retrans 1
  set_sysctl /proc/sys/net/ipv4/fib_multipath_use_neigh 1
  set_sysctl /proc/sys/net/ipv4/ipfrag_time 0
  set_sysctl /proc/sys/net/ipv4/xfrm4_gc_thresh 0
  set_sysctl /proc/sys/net/ipv4/tcp_app_win 0
  set_sysctl /proc/sys/net/ipv4/tcp_ecn_fallback 0
  set_sysctl /proc/sys/net/ipv4/tcp_invalid_ratelimit 0
  set_sysctl /proc/sys/net/ipv4/tcp_timestamps 0
  set_sysctl /proc/sys/net/ipv4/tcp_moderate_rcvbuf 0
  set_sysctl /proc/sys/net/ipv4/tcp_ecn 0
  set_sysctl /proc/sys/net/ipv4/tcp_slow_start_after_idle 0
  set_sysctl /proc/sys/net/ipv4/tcp_frto 0
}

# Função para configurar parâmetros de roteamento
configure_routing() {
  set_sysctl /proc/sys/net/ipv4/route/max_size 32768
  set_sysctl /proc/sys/net/ipv4/route/gc_thresh 16384
  set_sysctl /proc/sys/net/ipv4/route/gc_elasticity 16384
  set_sysctl /proc/sys/net/ipv4/route/gc_interval 120
  set_sysctl /proc/sys/net/ipv4/route/mtu_expires 15
  set_sysctl /proc/sys/net/ipv4/route/gc_timeout 15
  set_sysctl /proc/sys/net/ipv4/route/min_adv_mss 1024
  set_sysctl /proc/sys/net/ipv4/route/min_pmtu 1024
}

# Função para desativar IPv6
disable_ipv6() {
  set_sysctl /proc/sys/net/ipv6/conf/all/disable_ipv6 1
  set_sysctl /proc/sys/net/ipv6/conf/default/disable_ipv6 1
  set_sysctl /proc/sys/net/ipv6/conf/lo/disable_ipv6 1
}

# Executa todas as funções de configuração
configure_kernel
configure_network_core
configure_tcp
configure_routing
disable_ipv6

echo "Configurações aplicadas com sucesso."
