#!/bin/bash 
fun_badvpn() {
    clear
    echo -e "\033[0;34m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
    echo -e "\033[0;34m┃\E[44;1;37m            GERENCIAR BADVPN             \E[0m\033[0;34m┃"
    echo -e "\033[0;34m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\033[0m"
    if ps x | grep -w udpvpn | grep -v grep 1>/dev/null 2>/dev/null; then
        echo -e "\033[1;33mPORTAS\033[1;37m: \033[1;32m$(netstat -nplt | grep 'badvpn-ud' | awk {'print $4'} | cut -d: -f2 | xargs)"
    else
        sleep 0.1
    fi
    var_sks1=$(ps x | grep "udpvpn" | grep -v grep 1>/dev/null 2>/dev/null && echo -e "\033[1;32m♦ " || echo -e "\033[1;31m○ ")
    echo ""
    echo -e "\E[38;5;196m|\E[38;5;33m01\E[38;5;196m|\033[1;37m➜ \033[1;33mATIVAR BADVPN(PADRÃO 7300) $var_sks1 \033[0m"
    echo -e "\E[38;5;196m|\E[38;5;33m02\E[38;5;196m|\033[1;37m➜ \033[1;33mATIVAR AS PORTAS BADVPN (7100-7900)\033[0m"
    echo -e "\E[38;5;196m|\E[38;5;33m03\E[38;5;196m|\033[1;37m➜• \033[1;33mABRIR PORTA\033[0m"
    echo -e "\E[38;5;196m|\E[38;5;33m00\E[38;5;196m|\033[1;37m➜ \033[1;33mVOLTAR\033[0m"
    echo ""
    echo -ne "\033[1;32mO QUE DESEJA FAZER \033[1;33m?\033[1;37m "
    read resposta
    if [[ "$resposta" = '1' ]]; then
        if ps x | grep -w udpvpn | grep -v grep 1>/dev/null 2>/dev/null; then
            tput reset
            fun_stopbad () {
                for pidudpvpn in $(screen -ls | grep ".udpvpn" | awk {'print $1'}); do
                    screen -r -S "$pidudpvpn" -X quit
                done
                if [[ $(grep -wc "udpvpn" /etc/autostart) != '0' ]]; then
                    sed -i '/udpvpn/d' /etc/autostart
                fi
                sleep 1
                screen -wipe >/dev/null
            }
            echo -e "\033[1;32mDESATIVANDO O BADVPN\033[1;33m"
            fun_stopbad
            echo ""
            echo -e "\033[1;32mBADVPN DESATIVADO COM SUCESSO!\033[1;33m"
            sleep 0.5
            tput reset
            fun_badvpn
        else
            tput reset
            fun_udpon () {
                screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 10000 --max-connections-for-client 8
                if [[ $(grep -wc "udpvpn" /etc/autostart) = '0' ]]; then
                    echo -e "ps x | grep 'udpvpn' | grep -v 'grep' || screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 10000 --max-connections-for-client 8 --client-socket-sndbuf 10000" >> /etc/autostart
                else
                    sed -i '/udpvpn/d' /etc/autostart
                    echo -e "ps x | grep 'udpvpn' | grep -v 'grep' || screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 10000 --max-connections-for-client 8 --client-socket-sndbuf 10000" >> /etc/autostart
                fi
                sleep 1
            }
            inst_udp () {
                [[ -e "/bin/badvpn-udpgw" ]] && {
                    sleep 0.1
                } || {
                    cd $HOME
                    wget -qO- https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/Install/badvpn-udpgw -O /bin/badvpn-udpgw > /dev/null 2>&1
                    chmod 777 /bin/badvpn-udpgw
                fi
                echo -e "\033[1;32mINICIANDO O BADVPN... \033[1;33m"
                fun_udpon
                echo ""
                echo -e "\033[1;32mBADVPN ATIVADO COM SUCESSO\033[1;33m"
                sleep 0.5
                tput reset
                sleep 0.5
                fun_badvpn
            }
            inst_udp
        fi
    elif [[ "$resposta" = '2' ]]; then
        if ps x | grep -w udpvpn | grep -v grep 1>/dev/null 2>/dev/null; then
            tput reset
            echo -e "\033[0;34m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
            echo -e "\033[0;34m┃\E[44;1;37m            GERENCIAR BADVPN             \E[0m\033[0;34m┃"
            echo -e "\033[0;34m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\033[0m\n"
            echo -e "\033[1;32mINICIANDO TODAS AS PORTAS BADVPN... \033[0m"
            sleep 0.5
            echo -e ""
            echo -e "\033[1;32mPORTAS FECHAM AO REINICIAR A MAQUINA \033[0m"
            sleep 1.5
            for port in {7100..7900..100}; do
                screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:$port --max-clients 9000 --max-connections-for-client 8 --client-socket-sndbuf 10000 --udp-mtu 9000
            done
            echo -e ""
            echo -e "\033[1;32mPORTAS BADVPN ATIVADAS... \033[0m\n"
            sleep 0.5
            tput reset
            sleep 0.5
            fun_badvpn
        fi
    elif [[ "$resposta" = '3' ]]; then
        if ps x | grep -w udpvpn | grep -v grep 1>/dev/null 2>/dev/null; then
            tput reset
            echo -e "\033[0;34m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
            echo -e "\033[0;34m┃\E[44;1;37m            GERENCIAR BADVPN             \E[0m\033[0;34m┃"
            echo -e "\033[0;34m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\033[0m\n"
            echo -ne "\033[1;32mQUAL PORTA DESEJA UTILIZAR \033[1;33m?\033[1;37m: "
            read porta
            if [[ -z "$porta" ]]; then
                echo ""
                echo -e "\033[1;31mPorta inválida!\033[0m"
                sleep 0.5
                tput reset
                fun_badvpn
            fi
            fun_abrirptbad() {
                screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:$porta --max-clients 10000 --max-connections-for-client 8
            }
            echo -e "\033[1;32mABRINDO PORTA $porta BADVPN\033[1;33m"
            fun_abrirptbad
            echo ""
            echo -e "\033[1;32mPORTA BADVPN $porta ABERTA COM SUCESSO\033[1;33m"
            sleep 0.5
            tput reset
            fun_badvpn
        fi
    elif [[ "$resposta" = '0' ]]; then
        tput reset
        menu
    else
        tput reset
        fun_badvpn
    fi
}

fun_badvpn
