#!/bin/bash

clear

# Função para mostrar uma barra de progresso
fun_prog () {
    comando="$1"
    $comando > /dev/null 2>&1 &
    tput civis
    echo -ne "\033[1;32m.\033[1;33m.\033[1;31m. \033[1;32m"
    while [ -d /proc/$! ]; do
        for i in / - \\ \|; do
            sleep .1
            echo -ne "\e[1D$i"
        done
    done
    tput cnorm
    echo -e "\e[1DOK"
}

# Reiniciar OpenSSH
echo -ne "\033[1;33mREINICIANDO OPENSSH "; fun_prog 'service ssh restart'
echo ""
sleep 1

# Reiniciar Squid Proxy
if [[ -e /etc/squid/squid.conf ]]; then
    echo -ne "\033[1;33mREINICIANDO SQUID PROXY "; fun_prog 'service squid restart'
elif [[ -e /etc/squid3/squid.conf ]]; then
    echo -ne "\033[1;33mREINICIANDO SQUID PROXY "; fun_prog 'service squid3 restart'
fi
echo ""
sleep 1

# Reiniciar SSL Tunnel
if [[ -e /etc/stunnel/stunnel.conf ]]; then
    echo -ne "\033[1;33mREINICIANDO SSL TUNNEL "; fun_prog 'service stunnel4 restart'
fi
echo ""
sleep 1

# Reiniciar Dropbear
if [[ -e /etc/init.d/dropbear ]]; then
    echo -ne "\033[1;33mREINICIANDO DROPBEAR "; fun_prog 'service dropbear restart'
fi
echo ""
sleep 1

# Reiniciar OpenVPN
if [[ -e /etc/openvpn/server.conf ]]; then
    echo -ne "\033[1;33mREINICIANDO OPENVPN "; fun_prog 'service openvpn restart'
fi
echo ""
sleep 1

# Reiniciar Apache2
if netstat -nltp | grep 'apache2' > /dev/null; then
    echo -ne "\033[1;33mREINICIANDO APACHE2 "; fun_prog '/etc/init.d/apache2 restart'
fi
echo ""
sleep 1

# Reiniciar Stunnel4 (duplicado)
echo -ne "\033[1;33mREINICIANDO STUNNEL4 "; fun_prog '/etc/init.d/stunnel4 restart'
echo "" 

echo -e "\033[1;32mSERVIÇOS REINICIADOS COM SUCESSO!\033[0m"
sleep 1
