#!/bin/bash

# Get current version and public IP
_lvk=$(wget -qO- https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/versao)
IP=$(wget -qO- ipv4.icanhazip.com)
IP2=$(wget -qO- http://whatismyip.akamai.com/)
[[ "$IP" != "$IP2" ]] && ipdovps="$IP2" || ipdovps="$IP"
echo -e "$ipdovps" > /etc/IP

# Timezone configuration
echo -e "America/Sao_Paulo" > /etc/timezone
ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime >/dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata >/dev/null 2>&1

# Directory setup
dirs=(
    "/etc/SSHPlus"
    "/etc/SSHPlus/v2ray"
    "/etc/SSHPlus/proxy"
    "/etc/SSHPlus/openvpn"
    "/etc/SSHPlus/criarusuario"
    "/etc/SSHPlus/senha"
    "/etc/SSHPlus/userteste"
    "/etc/SSHPlus/suspenderusuario"
    "/etc/SSHPlus/.tmp"
    "/etc/bot"
    "/etc/bot/info-users"
    "/etc/bot/arquivos"
    "/etc/bot/revenda"
    "/etc/bot/suspensos"
    "/etc/rec"
)
for dir in "${dirs[@]}"; do
    [[ ! -d $dir ]] && mkdir -p $dir
done

# File setup
files=(
    "/etc/SSHPlus/Exp"
    "/etc/bot/lista_ativos"
    "/etc/bot/lista_suspensos"
)
for file in "${files[@]}"; do
    [[ ! -e $file ]] && touch $file
done

# Licence and credits
echo -e 'by: @KIRITO_SSH' > /usr/lib/sshplus
cat /usr/lib/sshplus > $lst2/licence
cat /usr/lib/sshplus > /etc/SSHPlus/.tmp/crazy

# Apache and SSH configuration
netstat -nplt | grep -w 'apache2' | grep -w '80' && sed -i "s/Listen 80/Listen 81/g" /etc/apache2/ports.conf && service apache2 restart
[[ "$(grep -o '#Port 22' /etc/ssh/sshd_config)" == "#Port 22" ]] && sed -i "s;#Port 22;Port 22;" /etc/ssh/sshd_config && service ssh restart
grep -v "^PasswordAuthentication" /etc/ssh/sshd_config > /tmp/passlogin && mv /tmp/passlogin /etc/ssh/sshd_config
echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config

# Module download and setup
_dir1='/bin'
_dir2='/etc/SSHPlus'
modules=(
    "addhost" "ajuda" "alterarlimite" "alterarsenha" "apache2menu" "autoreboot.sh" "tcptweaker.sh" "checkers" "utili" "multi" "check"
    "chuser" "limit" "rps_cpu" "attscript" "Autobackup" "backup_mail.sh" "badvpn" "badpro" "badpro1" "badvpn2" "badvpn3" "banner"
    "bashtop" "ddos" "blocksite" "blockt" "blockuser" "bot" "botssh" "cabecalho" "conexao" "criarteste" "criarusuario" "delhost"
    "delscript" "detalhes" "dns-netflix.sh" "droplimiter" "expcleaner" "ban.sh" "fr" "GoLang.sh" "infousers" "inst-botteste" "initcheck"
    "instsqd" "limiter" "menu" "menub" "menub2" "menuudp" "mudardata" "mtuning" "multi" "onlineapp" "open.py" "otimizar" "painelv2ray"
    "prissh" "prnet.sh" "proxydt" "proxy.py" "psiphon.sh" "reiniciarservicos" "reiniciarsistema" "remover" "senharoot" "ShellBot.sh"
    "slowdns" "speedtest" "sshmonitor" "suspenderusuario.sh" "swapmemory" "trafegototal" "trojan-go" "uexpired" "userbackup" "velocity"
    "verifatt" "verifbot" "v2raymanager" "webmin.sh" "websocket.sh" "wireguard.sh" "wsproxy.py" "pkill.sh"
)
for module in "${modules[@]}"; do
    [[ -e $_dir1/$module ]] && rm $_dir1/$module >/dev/null 2>&1
    wget -c -P $_dir1 https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/Modulos/$module
    chmod +x $_dir1/$module
done
mv $_dir1/{cabecalho,bot,open.py,proxy.py,wsproxy.py} $_dir2

# Hosts setup
_arq_host="/etc/hosts"
hosts=(
    "d1n212ccp6ldpw.cloudfront.net"
    "dns.whatsapp.net"
    "portalrecarga.vivo.com.br/recarga"
    "navegue.vivo.com.br/controle/"
    "navegue.vivo.com.br/pre/"
    "www.whatsapp.net"
    "/SSHPLUS?"
)
for host in "${hosts[@]}"; do
    if [[ "$(grep -w "$host" $_arq_host | wc -l)" == "0" ]]; then
        sed -i "3i\127.0.0.1 $host" $_arq_host
    fi
done

# Autostart setup
[[ ! -e /etc/autostart ]] && {
    echo '#!/bin/bash
clear
#INICIO AUTOMATICO' > /etc/autostart
    chmod +x /etc/autostart
} || {
    [[ $(ps x | grep "bot_plus" | grep -v grep | wc -l) != '0' ]] && wget -qO- https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/Install/ShellBot.sh
    for proc in $(ps x | grep 'dmS' | grep -v 'grep' | awk {'print $1'}); do
        screen -r -S "$proc" -X quit
    done
    screen -wipe >/dev/null
    echo '#!/bin/bash
clear
#INICIO AUTOMATICO' > /etc/autostart
    chmod +x /etc/autostart
}

# Cron job setup
crontab -r >/dev/null 2>&1
(
    crontab -l 2>/dev/null
    echo "@daily /bin/verifatt"
    echo "@reboot /etc/autostart"
    echo "* * * * * /etc/autostart"
    echo "0 */6 * * * /bin/uexpired"
) | crontab -

# Additional setup
echo "$_lvk" | sed -n '1 p' | cut -d' ' -f2 > /bin/versao && cat /bin/versao > /home/sshplus
wget https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/Install/jq-linux64 >/dev/null 2>&1
chmod +x jq-linux64 && mv jq-linux64 $(which jq)
service cron restart >/dev/null 2>&1
service ssh restart >/dev/null 2>&1
[[ -d /var/www/html/openvpn ]] && service apache2 restart >/dev/null 2>&1
rm -rf $lst1/list >/dev/null 2>&1
mkdir /opt/sshplus
echo > /opt/sshplus/sshplus

# Download WebSocket and keys
cd /etc/SSHPlus/
wget https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/Modulos/WebSocket
wget https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/Modulos/pub.key
wget https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/Modulos/priv.pem
chmod 777 WebSocket

# Download and setup proxydt
cd /etc/SSHPlus/
wget https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/Modulos/proxydt
chmod 777 proxydt

# Return to home directory
cd $HOME
